Repository herbsjs/herbsshelf, pull requests merged in 2022-01, with the labels that each got.

#32 fix(shelf.css): fix icons for dark mode
  src/css/shelf.css
Labels: bug, severity-minor, wip

#33 fix: fix if else representation
  .eslintrc.json
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push.yml
  package-lock.json
  package.json
  src/css/shelf.css
  src/template/components/stepsCard.js
  src/template/default.js
Labels: bug, dependencies, severity-major

#34 ci: fix gitactions
  .github/workflows/cd.yml
Labels: dependencies, severity-major
